#Use a base image of ubi8/ubi:8.5 and set an arbitrary maintainer.
FROM ubi8/ubi:8.5

MAINTAINER Joseph Krenek <joseph.krenek@us.ibm.com>

#Set the ARG variable NEXUS_VERSION to 2.14.3-02, and 
ARG NEXUS_VERSION=2.14.3-02

#set the environment variable NEXUS_HOME to /opt/nexus.
ENV NEXUS_HOME=/opt/nexus

#Unpack the nexus-2.14.3-02-bundle.tar.gz file to the ${NEXUS_HOME}/
#directory. Add the nexus-start.sh to the same directory.
ADD nexus-${NEXUS_VERSION}-bundle.tar.gz ${NEXUS_HOME}
ADD nexus-start.sh ${NEXUS_HOME}

#Install the java-1.8.0-openjdk-devel package.

#Run a command to create a nexus user and group. They both have a UID and GID of
#1001. Change the permissions of the ${NEXUS_HOME}/ directory to 775.

#Run a command, ln -s ${NEXUS_HOME}/nexus-${NEXUS_VERSION} ${NEXUS_HOME}/nexus2, to create a symlink in the container. 
#Run a command to recursively change the ownership of the Nexus home directory to nexus:nexus.
#yum install -y java-1.8.0-openjdk-devel &&
ARG NEXUS_ID=1001

#RUN groupadd --gid ${NEXUS_ID} --system --force nexus
#RUN useradd --uid ${NEXUS_ID} --gid ${NEXUS_ID} --system --home-dir ${NEXUS_HOME} --create-home --shell /sbin/nologin --comment "Nexus user" nexus
#RUN useradd --uid ${NEXUS_ID} --system --gid ${NEXUS_ID} --create-home --home-dir ${NEXUS_HOME} --shell /sbin/nologin --comment "Nexus User" nexus
RUN yum install -y java-1.8.0-openjdk-devel --setopt=tsflags=nodocs && yum clean all -y &&\
  groupadd --gid ${NEXUS_ID} nexus && \
  useradd --uid ${NEXUS_ID} --gid ${NEXUS_ID} --system --home-dir ${NEXUS_HOME} --create-home --shell /sbin/nologin --comment "Nexus user" nexus && \
  chmod --recursive 775 ${NEXUS_HOME} && \
  chown --recursive ${NEXUS_ID}:${NEXUS_ID} ${NEXUS_HOME} && \
  ln -s ${NEXUS_HOME}/nexus-${NEXUS_VERSION} ${NEXUS_HOME}/nexus2

#Make the container run as the nexus user, and set the working directory to /opt/ nexus.
USER nexus:nexus
WORKDIR ${NEXUS_HOME}

#Define a volume mount point for the /opt/nexus/sonatype-work container directory. The Nexus server stores data in this directory.
VOLUME ["/opt/nexus/sonatype-work"]

#Set the default container command to nexus-start.sh.
CMD ["sh", "nexus-start.sh"]
#ENTRYPOINT [ "${NEXUS_HOME}/nexus-start.sh" ]